# template.sub
# antismash

universe = vanilla
log = logs/job_$(Cluster).log
error = errors/job_$(Cluster)_$(Process).err
output = outputs/job_$(Cluster)_$(Process).out

executable = antismash_main.sh
arguments = $(filename)

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

request_cpus = 1
request_memory = 8GB
request_disk = 20GB
max_idle = 100

Requirements = (Target.HasCHTCStaging == true)

+WantGlideIn = true
+WantFlocking = true

transfer_input_files = antismash_cmd.sh, genomes/$(filename)

queue filename from sample_matrix.csv



