# Software build file

universe = vanilla
log = interactive.log

# change the name of the file to be the name of your source code
transfer_input_files = source_code.tar.gz
transfer_input_files = sg_conda.tar.gz, http://proxy.chtc.wisc.edu/SQUID/cmclark8/socialgene_nr_hmms_file_1_of_5.hmm.gz, sg_input_fasta/temp.faa.gz

+IsBuildJob = true
requirements = (OpSysMajorVer =?= 7)
request_cpus = 1
request_memory = 4GB
request_disk = 2GB

queue
